export const images = {
    remove: require("../Assets/close.png"),
    edit: require("../Assets/edit.png"),
    pin_map: require("../Assets/pin_map.png"),
    image_add: require("../Assets/image_add.png"),
    card_active: require("../Assets/card_active.png"),
    card_inactive: require("../Assets/card_inactive.png"),
    people_inactive: require("../Assets/people_inactive.png"),
    people_active: require("../Assets/people_active.png"),
    user_round: require("../Assets/user_round.png"),
    star: require("../Assets/star.png"),
    back_grey: require("../Assets/back_grey.png"),
    banner: require("../Assets/banner.png"),
    remove: require("../Assets/remove.png"),
}
